name: 'Deploy para AWS CloudFormation'

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout da branch
        uses: actions/checkout@v2

      - name: Deploy no CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with: 
          name: dataops-lab3
          template: ec2-jenkins.yaml
          parameter-overrides: "key=vockey,iamprofile=LabInstanceProfile"
