name: 'Deploy para AWS CloudFormation'

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout da branch
        uses: actions/checkout@v2